print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/gagehabiger/Desktop/Level-Design/Unity Project/Assets/Models/police.mb"`)
{		
	file -o "/Users/gagehabiger/Desktop/Level-Design/Unity Project/Assets/Models/police.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/gagehabiger/Desktop/Level-Design/Unity Project/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/gagehabiger/Desktop/Level-Design/Unity Project/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/gagehabiger/Desktop/Level-Design/Unity Project/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
